name: Run Postman Sub-Collection

on:
  push:
    branches:
      - main  # Change this to your preferred branch

jobs:
  run-postman-sub-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change this to your preferred Node.js version

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Sub-Collection
      run: newman run git_API.json  # Replace with your sub-collection file name
